# XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#CONSTANTS USED FOR OPENSTACK
#Constants for creating a VM.
FLAVOR_NAME=''
IMAGE_NAME=''
NETWORK_NAME=''
PROVIDER_NETWORK=''
KEY_NAME=''

#Constant for shade.
CLOUD_NAME='cloudprod'

#Minimal value for VCPU and memory for a VM.
MINIMAL_CPU=1
MINIMAL_MEM=1048576
# XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#CONSTANTS USED FOR LIBVIRT
#Constant to create a connection to hypervisor.
CONNECTION_LIBVIRT_TEMPLATE = "qemu+tcp://{0}/system"
# XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#CONSTANTS USED FOR RABBITMQ
RABBIT_USER = "rabbit_user"
RABBIT_PASSWD = "rabbit_passwd"
RABBIT_IP = "rabbit_ip"
RABBIT_PORT = 5672
RABBIT_SCALER_QUEUE = "scaler-requests"

#LOGGING FOR AGENT
LOGGER_NAME = 'Scaler.Agent'
LOG_FILE_NAME = '/var/log/scaler-agent.log'
# XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
