# XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#CONSTANTS USED FOR RABBITMQ IN CLIENT SIDE
RABBIT_USER = "rabbit_user"
RABBIT_PASSWD = "rabbit_passwd"
RABBIT_IP = "rabbit_ip"
RABBIT_PORT = 5672
RABBIT_CLIENT_QUEUE = "client-requests"
RABBIT_SCALER_QUEUE = "scaler-requests"

DEFAULT_WINDOW_TIME = 10
VNF_IMAGE_PROCESSING = "is_image_processing"
IS_SPACE_CONFIG_PATH = '/usr/local/ispace/cloud-nerds-ispace'
# XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
