# XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#CONSTANTS USED FOR RABBITMQ
RABBIT_USER = "rabbit_user"
RABBIT_PASSWD = "rabbit_passwd"
RABBIT_IP = "rabbit_ip"
RABBIT_PORT = 5672
RABBIT_CLIENT_QUEUE = "client-requests"
RABBIT_SCALER_QUEUE = "scaler-requests"
# XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
